version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: tinyurl-mysql
    environment:
      MYSQL_DATABASE: tinyurl
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: tinyurl-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tinyurl?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      PUBLIC_DOMAIN: tinyurlnaga-nixpacksjavaversion17.up.railway.app

volumes:
  mysql-data:
